Update benchmark and control tags for compatibility with dashboard page Closes #26
turbot/steampipe-mod-azure-thrifty pull request #27
Opened 2022-04-28 14:44 UTC by khushboo9024

### Checklist
- [ ] Issue(s) linked

2022-04-29 19:26 UTC, cbruno10 requested changes
Please see suggestion, thanks!

2022-04-29 19:26 UTC, cbruno10 commented on controls/sql.sp
> +    service = "Azure/SQLDatabase"
```suggestion
    service = "Azure/SQL"
```

2022-04-29 19:26 UTC, cbruno10 commented on controls/sql.sp
> +    service = "Azure/SQLDatabase"
If unsure of what the service should be called, please check the Azure Insights mod first and see what it's called there.

2022-05-02 13:07 UTC, rajlearner17 approved these changes
LGTM

2022-05-02 13:12 UTC, merged